### PR TITLE
Some changes to sim info and maxr fix

### PR DESCRIPTION
**Pull request by sophiemiddleton**
Includes two features:

* Move proc --> startCode
* maxr fix

### CODE REVIEW

**Comment by sophiemiddleton** [comment]
lots of. diffs, I guess I need to rebase to the dev branch, its not an immediate need anyway

**Comment by AndrewEdmonds11** [comment]
Thanks, Sophie. I think it's just because I haven't merged main into v05-dev yet. This PR might look cleaner once I do that. By the way, does the maxr fix not need to go into v4 too?

**Comment by sophiemiddleton** [comment]
yes, it should go into that too I guess, I'm not sure if anyone but me is using it but I could put in two PR's if you'd prefer?

**Comment by AndrewEdmonds11** [comment]
Thanks, Sophie. Two PRs would be great :)

**Pull request merged**
